/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeritasRegistry } from "./VeritasRegistry";
export * as factories from "./factories";
export { VeritasRegistry__factory } from "./factories/VeritasRegistry__factory";
