/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VeritasRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isDeviceTrusted"
      | "owner"
      | "registerDevice"
      | "revokeDevice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DeviceRegistered" | "DeviceRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "isDeviceTrusted",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDevice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDevice",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isDeviceTrusted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDevice",
    data: BytesLike
  ): Result;
}

export namespace DeviceRegisteredEvent {
  export type InputTuple = [publicKey: string, timestamp: BigNumberish];
  export type OutputTuple = [publicKey: string, timestamp: bigint];
  export interface OutputObject {
    publicKey: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRevokedEvent {
  export type InputTuple = [publicKey: string, timestamp: BigNumberish];
  export type OutputTuple = [publicKey: string, timestamp: bigint];
  export interface OutputObject {
    publicKey: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeritasRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VeritasRegistry;
  waitForDeployment(): Promise<this>;

  interface: VeritasRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isDeviceTrusted: TypedContractMethod<[publicKey: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerDevice: TypedContractMethod<
    [publicKey: string],
    [void],
    "nonpayable"
  >;

  revokeDevice: TypedContractMethod<[publicKey: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isDeviceTrusted"
  ): TypedContractMethod<[publicKey: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDevice"
  ): TypedContractMethod<[publicKey: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeDevice"
  ): TypedContractMethod<[publicKey: string], [void], "nonpayable">;

  getEvent(
    key: "DeviceRegistered"
  ): TypedContractEvent<
    DeviceRegisteredEvent.InputTuple,
    DeviceRegisteredEvent.OutputTuple,
    DeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRevoked"
  ): TypedContractEvent<
    DeviceRevokedEvent.InputTuple,
    DeviceRevokedEvent.OutputTuple,
    DeviceRevokedEvent.OutputObject
  >;

  filters: {
    "DeviceRegistered(string,uint256)": TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;
    DeviceRegistered: TypedContractEvent<
      DeviceRegisteredEvent.InputTuple,
      DeviceRegisteredEvent.OutputTuple,
      DeviceRegisteredEvent.OutputObject
    >;

    "DeviceRevoked(string,uint256)": TypedContractEvent<
      DeviceRevokedEvent.InputTuple,
      DeviceRevokedEvent.OutputTuple,
      DeviceRevokedEvent.OutputObject
    >;
    DeviceRevoked: TypedContractEvent<
      DeviceRevokedEvent.InputTuple,
      DeviceRevokedEvent.OutputTuple,
      DeviceRevokedEvent.OutputObject
    >;
  };
}
